# Generated by Django 4.0.4 on 2022-05-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlCurta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlOriginal', models.CharField(max_length=100)),
                ('urlEncurtada', models.CharField(max_length=50)),
            ],
        ),
    ]
